// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using RaceHub.Motors.API.DAL.Entity;

namespace RaceHub.Motors.API.DAL.Context
{
    public partial class RaceHubMotorsContext : DbContext
    {
        public RaceHubMotorsContext(DbContextOptions<RaceHubMotorsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Drivetrain> Drivetrains { get; set; }

        public virtual DbSet<Engine> Engines { get; set; }

        public virtual DbSet<VehicleColor> VehicleColors { get; set; }

        public virtual DbSet<Manufacturer> Manufacturers { get; set; }

        public virtual DbSet<Vehicle> Vehicles { get; set; }

        public virtual DbSet<VehicleType> VehicleTypes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Drivetrain>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Drivetra__3214EC0788606B2D");

                entity.ToTable("Drivetrain", "Cfg");

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(5)
                    .IsUnicode(false);
                entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.CreatedBy)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(suser_sname())");
                entity.Property(e => e.Description)
                    .HasMaxLength(30)
                    .IsUnicode(false);
                entity.Property(e => e.LastUpd).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.LastUpdApp)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(app_name())");
                entity.Property(e => e.LastUpdBy)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(suser_sname())");
            });

            modelBuilder.Entity<Engine>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Engine__3214EC07D8E6028E");

                entity.ToTable("Engine", "Cfg");

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(3)
                    .IsUnicode(false);
                entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.CreatedBy)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(suser_sname())");
                entity.Property(e => e.Description)
                    .HasMaxLength(20)
                    .IsUnicode(false);
                entity.Property(e => e.LastUpd).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.LastUpdApp)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(app_name())");
                entity.Property(e => e.LastUpdBy)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(suser_sname())");
            });

            modelBuilder.Entity<VehicleColor>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__VehicleC__3214EC074CA9A7E0");

                entity.ToTable("VehicleColor", "Cfg");

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
                entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.CreatedBy)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(suser_sname())");
                entity.Property(e => e.Description)
                    .HasMaxLength(30)
                    .IsUnicode(false);
                entity.Property(e => e.LastUpd).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.LastUpdApp)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(app_name())");
                entity.Property(e => e.LastUpdBy)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasDefaultValueSql("(suser_sname())");
            });

            modelBuilder.Entity<Manufacturer>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Manufact__3214EC073E4EC42C");

                entity.ToTable("Manufacturer", "Manufacturer");

                entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.CreatedBy).IsRequired().HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(suser_sname())");
                entity.Property(e => e.LastUpd).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.Name).IsRequired().HasMaxLength(50).IsUnicode(false);
                entity.Property(e => e.Country).IsRequired().HasMaxLength(30).IsUnicode(false);
                entity.Property(e => e.CountryCode).IsRequired().HasMaxLength(10).IsUnicode(false);
                entity.Property(e => e.Region).IsRequired().HasMaxLength(10).IsUnicode(false);
                entity.Property(e => e.LastUpdBy).IsRequired().HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(suser_sname())");
                entity.Property(e => e.LastUpdApp).IsRequired().HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(app_name())");
            });

            modelBuilder.Entity<Vehicle>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__Vehicle__3214EC0759A04D38");

                entity.ToTable("Vehicle", "Vehicle");

                entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.CreatedBy).IsRequired().HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(suser_sname())");
                entity.Property(e => e.LastUpd).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.LastUpdBy).IsRequired().HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(suser_sname())");
                entity.Property(e => e.LastUpdApp).IsRequired().HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(app_name())");
                entity.Property(e => e.VehImage).IsRequired().IsUnicode(false);
                entity.Property(e => e.TypeCode).IsRequired().IsUnicode(false);
                entity.Property(e => e.VehYear).IsRequired();
            });

            modelBuilder.Entity<VehicleType>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__VehicleT__3214EC073EBFD425");

                entity.ToTable("VehicleType", "Vehicle");

                entity.Property(e => e.TypeCode).IsRequired().HasMaxLength(5).IsUnicode(false);
                entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.CreatedBy).IsRequired().HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(suser_sname())");
                entity.Property(e => e.Description).IsRequired().HasMaxLength(50).IsUnicode(false);
                entity.Property(e => e.LastUpd).HasDefaultValueSql("(getdate())");
                entity.Property(e => e.LastUpdApp).IsRequired().HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(app_name())");
                entity.Property(e => e.LastUpdBy).IsRequired().HasMaxLength(50).IsUnicode(false).HasDefaultValueSql("(suser_sname())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}