// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaceHub.Motors.API.DAL.Entity
{
    public partial class Drivetrain
    {
        public int Id { get; set; }

        public string Code { get; set; }

        public string Description { get; set; }

        public DateTime Created { get; set; }

        public string CreatedBy { get; set; }

        public DateTime LastUpd { get; set; }

        public string LastUpdBy { get; set; }

        public string LastUpdApp { get; set; }
    }
}